server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# CORS básico
dmh:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}

jwt:
  # Base64
  secret: ${JWT_SECRET:UmFuZG9tU2VjcmV0S2V5Rm9yRE1ILUdhdGV3YXk=}
